language: python
python:
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.5-dev"
 - "nightly"
install:
 - pip install pylint requests
script:
 - python3 -m pylint -r n -d bad-whitespace,bad-continuation,missing-docstring,multiple-imports,locally-disabled instaloader
