language: python
python:
 - "3.5"
 - "3.5-dev"
 - "3.6"
 - "3.6-dev"
 - "3.7-dev"
 - "nightly"
install:
 - pip install pylint requests
script:
 - python3 -m pylint -r n -d bad-whitespace,bad-continuation,missing-docstring,multiple-imports,too-many-arguments,locally-disabled,line-too-long,invalid-sequence-index,raising-bad-type instaloader
